### ISSUE TITLE
no implicit conversion of nil into Array (TypeError)

### ISSUE THREAD

**Issue by emacsomancer** [rlue/little_red_flag#2]
```
$ littleredflag -av
[16-MAY-2017 21:49:22] Parsing configuration files...
/usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:218:in `-': no implicit conversion of nil into Array (TypeError)
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:218:in `block (3 levels) in populate_channel_inboxes'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:216:in `each'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:216:in `block (2 levels) in populate_channel_inboxes'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:212:in `each'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:212:in `block in populate_channel_inboxes'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:210:in `each'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:210:in `populate_channel_inboxes'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:144:in `postprocess'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:76:in `initialize'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync.rb:10:in `new'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync.rb:10:in `initialize'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent.rb:12:in `new'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent.rb:12:in `new'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/bin/littleredflag:37:in `block in <top (required)>'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/bin/littleredflag:37:in `map!'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.2/bin/littleredflag:37:in `<top (required)>'
        from /usr/bin/littleredflag:22:in `load'
        from /usr/bin/littleredflag:22:in `<main>'

```

**Comment by rlue** [comment]
Oops, I think I know what happened – do you have patterns in any of your channels that fit the following format?

    !".*"

I made a mistake in a monkeypatched method when refactoring, but it's fixed now. Try v0.1.3?

**Comment by emacsomancer** [comment]
I'm still getting errors now:

```
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pry (LoadError)
        from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/gems/2.4.0/gems/little_red_flag-0.1.6/bin/littleredflag:6:in `<top (required)>'
        from /usr/bin/littleredflag:22:in `load'
        from /usr/bin/littleredflag:22:in `<main>'

```

**Comment by emacsomancer** [comment]
any update on this? (I'd really love to start using littleredflag)

**Comment by rlue** [comment]
It needs a serious overhaul (writing specs and refactoring some classes), so it might be a couple weeks before I can get that done. Thanks for your patience!

**Comment by emacsomancer** [comment]
Thanks, @rlue . I'm looking forward to it. This is essentially the one thing missing from my mu4e-mbsync setup.
