### ISSUE TITLE
undefined method `downcase' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by hsanson** [rlue/little_red_flag#3]
Running this tool I get this error:

```
[~]> littleredflag -a
/var/lib/gems/2.3.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:21:in `connect': undefined method `downcase' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:211:in `block in populate_channel_inboxes'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:210:in `each'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:210:in `populate_channel_inboxes'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:144:in `postprocess'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync/config.rb:76:in `initialize'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync.rb:10:in `new'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent/mbsync.rb:10:in `initialize'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent.rb:12:in `new'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.2/lib/little_red_flag/mail_agent.rb:12:in `new'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.2/bin/littleredflag:37:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.2/bin/littleredflag:37:in `map!'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.2/bin/littleredflag:37:in `<top (required)>'
        from /usr/local/bin/littleredflag:23:in `load'
        from /usr/local/bin/littleredflag:23:in `<main>'
```

**Comment by rlue** [comment]
Appears to be related to Issue #2, and hopefully fixed now. Try 

    gem update little_red_flag

then run again and let me know?

**Comment by hsanson** [comment]
Unfortunately not solved with 0.1.3:

```
littleredflag                                                                                   
/var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync/config.rb:21:in `connect': undefinedmethod `downcase' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync/config.rb:211:in `blockin populate_channel_inboxes'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync/config.rb:210:in `each'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync/config.rb:210:in `populate_channel_inboxes'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync/config.rb:144:in `postprocess'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync/config.rb:76:in `initialize'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync.rb:10:in `new'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync.rb:10:in `initialize'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent.rb:12:in `new'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent.rb:12:in `new'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/bin/littleredflag:37:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/bin/littleredflag:37:in `map!'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/bin/littleredflag:37:in `<top (required)>'
        from /usr/local/bin/littleredflag:23:in `load'
        from /usr/local/bin/littleredflag:23:in `<main>'
```

Looking at the trace the problem seems to be that `ssltype` is nil:

```
21: imap = Net::IMAP.new(host, port: port, ssl: (ssltype.downcase == 'imaps'))
```

And I do have an IMAP account that does not use IMAPS:

```
IMAPAccount xxxx@email.net
Host mail.email.net
User xxxx@email.net
Pass secretPassWord
UseIMAPS no
RequireSSL no
```

I am trying to create the smallest config file that reproduces the issue but when I delete other parts of the config I get a different error:

```
/var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync/config.rb:187:in `block in link_group_channels': undefined method `map!' for "xxxxx-email-inbox":String (NoMethodError)
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync/config.rb:186:in `each'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync/config.rb:186:in `link_group_channels'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync/config.rb:142:in `postprocess'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync/config.rb:76:in `initialize'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync.rb:10:in `new'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent/mbsync.rb:10:in `initialize'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent.rb:12:in `new'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/lib/little_red_flag/mail_agent.rb:12:in `new'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/bin/littleredflag:37:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/bin/littleredflag:37:in `map!'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.3/bin/littleredflag:37:in `<top (required)>'
        from /usr/local/bin/littleredflag:23:in `load'
        from /usr/local/bin/littleredflag:23:in `<main>'
```

BTW: Would be nice to have a flag option to use a different .mbsyncrc file so I do not have to modify my main configuration to debug this.

**Comment by rlue** [comment]
v0.1.4 should check that `ssltype` is not nil before trying to apply the `#downcase` method.

Three version bumps in one day. How embarrassing. The code is a bit of a mess right now tbh, but I intend to give it a hearty refactoring when I get some time to hunker down with it again.

Thanks for your help.

**Comment by hsanson** [comment]
First time I have had an issue solved within one hour of reporting!!. 

Last fix seems to be working, Thanks.
