### ISSUE TITLE
Network is unreachable - connect(2) for "imap.gmail.com" port 143 (Errno::ENETUNREACH)

### ISSUE THREAD

**Issue by hsanson** [rlue/little_red_flag#4]
After a while the deamon dies with the following error:

```
[17-MAY-2017 14:54:27] Parsing configuration files...                                                                     
/usr/lib/ruby/2.3.0/net/imap.rb:1082:in `initialize': Network is unreachable - connect(2) for "imap.gmail.com" port 143 (Errno::ENETUNREACH)
        from /usr/lib/ruby/2.3.0/net/imap.rb:1082:in `open'                                                               
        from /usr/lib/ruby/2.3.0/net/imap.rb:1082:in `initialize'                        
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/lib/little_red_flag/mail_agent/mbsync/config.rb:21:in `new'   
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/lib/little_red_flag/mail_agent/mbsync/config.rb:21:in `connect'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/lib/little_red_flag/mail_agent/mbsync/config.rb:211:in `blockin populate_channel_inboxes'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/lib/little_red_flag/mail_agent/mbsync/config.rb:210:in `each' 
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/lib/little_red_flag/mail_agent/mbsync/config.rb:210:in `populate_channel_inboxes'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/lib/little_red_flag/mail_agent/mbsync/config.rb:144:in `postprocess'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/lib/little_red_flag/mail_agent/mbsync/config.rb:76:in `initialize'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/lib/little_red_flag/mail_agent/mbsync.rb:10:in `new'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/lib/little_red_flag/mail_agent/mbsync.rb:10:in `initialize'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/lib/little_red_flag/mail_agent.rb:12:in `new'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/lib/little_red_flag/mail_agent.rb:12:in `new'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/bin/littleredflag:37:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/bin/littleredflag:37:in `map!'
        from /var/lib/gems/2.3.0/gems/little_red_flag-0.1.4/bin/littleredflag:37:in `<top (required)>'
        from /usr/local/bin/littleredflag:23:in `load'                                   
        from /usr/local/bin/littleredflag:23:in `<main>'
```

This should not die when there are connectivity issues that are common in laptops (my case) changing networks when moving from a desk to a conference room, etc.

**Comment by rlue** [comment]
That's _very_ strange – the method where this is getting caught is supposed to confirm that your connection works before trying to instantiate a new IMAP connection. As you can see below, it shouldn't exit the first `until` loop until you can successfully ping the IMAP server:

```ruby
def connect
  until Ping.new(host).ping
    10.downto(1) do |i|
      printf "#{host} unreachable. Trying again in #{i}s... \r"
      sleep 1
    end
    puts "#{host} unreachable. Trying again...          "
  end
  imap = Net::IMAP.new(host, port: port, ssl: (ssltype && (ssltype.downcase == 'imaps')))
  ...
end
```

For your connection to have dropped between the one and the other seems highly unlikely. Can you confirm your server settings? It looks like you're trying to connect to imap.gmail.com over port 143, but [according to Gmail's instructions, it looks like they want an SSL connection over port 993?](https://support.google.com/mail/answer/7126229?hl=en) I tried modifying the gmail IMAPAccount in my own `.mbsyncrc` to use port 143 and no SSL, but mbsync just hung instead.

**Comment by rlue** [comment]
You seem to be right about there being issues when your connection drops, though – from what I can see, IDLE connections don't get renewed after a dropped connection. I'm getting to work on that now.
