### ISSUE TITLE
Missing dependency - pry

### ISSUE THREAD

**Issue by oscarcarlsson** [rlue/little_red_flag#5]
I've just installed LRF on my machine, and after trying to run it I was met by an error message:

```
osccar@derp:~$ gem install little_red_flag
Fetching: rb-fsevent-0.10.2.gem (100%)
Successfully installed rb-fsevent-0.10.2
Fetching: ffi-1.9.18.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.18
Fetching: rb-inotify-0.9.10.gem (100%)
Successfully installed rb-inotify-0.9.10
Fetching: ruby_dep-1.5.0.gem (100%)
Successfully installed ruby_dep-1.5.0
Fetching: listen-3.1.5.gem (100%)
Successfully installed listen-3.1.5
Fetching: sys-proctable-1.1.4-universal-linux.gem (100%)
Successfully installed sys-proctable-1.1.4-universal-linux
Fetching: little_red_flag-0.1.6.gem (100%)
Successfully installed little_red_flag-0.1.6
Parsing documentation for rb-fsevent-0.10.2
Installing ri documentation for rb-fsevent-0.10.2
Parsing documentation for ffi-1.9.18
Installing ri documentation for ffi-1.9.18
Parsing documentation for rb-inotify-0.9.10
Installing ri documentation for rb-inotify-0.9.10
Parsing documentation for ruby_dep-1.5.0
Installing ri documentation for ruby_dep-1.5.0
Parsing documentation for listen-3.1.5
Installing ri documentation for listen-3.1.5
Parsing documentation for sys-proctable-1.1.4-universal-linux
Installing ri documentation for sys-proctable-1.1.4-universal-linux
Parsing documentation for little_red_flag-0.1.6
Installing ri documentation for little_red_flag-0.1.6
Done installing documentation for rb-fsevent, ffi, rb-inotify, ruby_dep, listen, sys-proctable, little_red_flag after 8 seconds
7 gems installed
osccar@derp:~$ littleredflag 
/home/osccar/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pry (LoadError)
	from /home/osccar/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/osccar/.rvm/gems/ruby-2.3.4/gems/little_red_flag-0.1.6/bin/littleredflag:6:in `<top (required)>'
	from /home/osccar/.rvm/gems/ruby-2.3.4/bin/littleredflag:22:in `load'
	from /home/osccar/.rvm/gems/ruby-2.3.4/bin/littleredflag:22:in `<main>'
	from /home/osccar/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
	from /home/osccar/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
```

Tested both on 2.4.1 and 2.3.4, printout is identical for both.

The current workaround: ```gem install pry```

**Comment by rlue** [comment]
Thanks for the heads up. FYI LRF needs a major overhaul and currently does not work on my machine. Should probably update the README to reflect that, or just get around to it this weekend.

**Comment by oscarcarlsson** [comment]
Ah, I was trying to figure out what wasn't working with my setup but I guess it won't work no matter what I try then. I don't know any ruby so can't help you with the overhaul :(
